#!/bin/bash
# Основан на скрипте  
# create_site_joomla.sh
# автор: Gurom  
# 16 Jan, 2011                    
#************************************************#
#              Создание виртуального домена  	 #
#                автор: WebCreate                #
#                9 May, 2011                     #
#************************************************#

# Устанавливаем название каталога где будут храниться проекты
WORK_DIR="projects"
#echo -e "\033[1mУкажите имя для папки в которой будут располагаться проекты:\033[0m"; read WORK_DIR
echo -e "\033[1mВведите название проекта:\033[0m"; read NAME_OF_PROJECT

# Cоздаем папки проекта
mkdir -p ~/$WORK_DIR/$NAME_OF_PROJECT/public
cd ~/$WORK_DIR/$NAME_OF_PROJECT/
mkdir cgi-bin logs

#указываем владельца и права на папку "public"
chmod -R 755 ~/$WORK_DIR/$NAME_OF_PROJECT/

# Создаем страничку в public для того чтобы сайт хоть что-то отражал
touch ~/$WORK_DIR/$NAME_OF_PROJECT/public/index.php
echo "<h2>It Works! $NAME_OF_PROJECT</h2><?php phpinfo(); ?>" >> ~/$WORK_DIR/$NAME_OF_PROJECT/public/index.php

#добавляем правила в конфигурационый файл апача
add_to_apache_conf="
<VirtualHost *:80>
ServerName $NAME_OF_PROJECT
        ServerAlias www.$NAME_OF_PROJECT
        ServerAdmin admin@$NAME_OF_PROJECT
        DocumentRoot $HOME/$WORK_DIR/$NAME_OF_PROJECT/public
        <Directory "$HOME/$WORK_DIR/$NAME_OF_PROJECT">
                Options Indexes FollowSymLinks MultiViews
                AllowOverride All
                Order allow,deny
                allow from all
        </Directory>

        ScriptAlias /cgi-bin/ $HOME/$WORK_DIR/$NAME_OF_PROJECT/cgi-bin/
        <Directory "$HOME/$WORK_DIR/$NAME_OF_PROJECT/cgi-bin">
                AllowOverride All
                Options +ExecCGI -MultiViews +SymLinksIfOwnerMatch
                Order allow,deny
                Allow from all
        </Directory>

        ErrorLog $HOME/$WORK_DIR/$NAME_OF_PROJECT/logs/error.log
        LogLevel warn
        CustomLog $HOME/$WORK_DIR/$NAME_OF_PROJECT/logs/access.log combined
</VirtualHost>"

add_to_hosts_conf="127.0.0.1 $NAME_OF_PROJECT"

#Добавляем новый хост
conf_file_name="$NAME_OF_PROJECT.conf"
sudo sh -c "echo '$add_to_hosts_conf' >> /etc/hosts"
if [ -f /etc/apache2/sites-available/$conf_file_name ]
then
	sudo rm /etc/apache2/sites-available/$conf_file_name
	echo -e "Удалили старый виртуальный хост и создали новый"
fi
sudo sh -c "touch /etc/apache2/sites-available/$conf_file_name"
sudo sh -c "echo '$add_to_apache_conf' >> /etc/apache2/sites-available/$conf_file_name"

#Включаем конфигурацию сайта
sudo a2ensite $conf_file_name
#sudo a2dissite

#Создаем БД
echo -e "\033[1mСоздать БД для проекта?(yes/no)\033[0m"
read CREATE_DB

if  [ "$CREATE_DB" = "yes" -o "$CREATE_DB" = "y" -o "$CREATE_BAZA" = "YES" ]; then
	#echo -e "\033[1mВведите имя базы данных:\033[0m";
	#read DB_NAME
	DB_NAME=${NAME_OF_PROJECT/./}
	echo -e "\033[1mВВедите пароль для нового пользователя ${NAME_OF_PROJECT}_user который будет обладать всем правами на вновь созданную базу:\033[0m";
	read -s DB_PASS
	# Создаем базу данных имя которой мы ввели
echo -e "\033[1mТеперь будет необходимо ввести 2 раза пароль root MySQL, если пароля нет, просто нажмите Enter\033[0m";
	mysql -uroot -p --execute="CREATE DATABASE $DB_NAME;"
	# Создаем нового пользователя
	mysql -uroot -p --execute="GRANT ALL PRIVILEGES ON $DB_NAME.* TO ${DB_NAME}_user@localhost IDENTIFIED by '$DB_PASS'  WITH GRANT OPTION;"

 echo -e "\033[1mБаза данных $NAME_OF_PROJECT создана.\033[0m";

else
     echo -e "\033[1mБаза данных не была создана\033[0m";
fi
echo "Перезапускаем apache..."
sudo /etc/init.d/apache2 reload

echo -e "\033[1mСоздаем конфигурационный файл проекта\033[0m";

touch ~/$WORK_DIR/$NAME_OF_PROJECT/config.txt
echo -e "Name Project: $NAME_OF_PROJECT\nDB_NAME:$DB_NAME\nDB_USER:${NAME_OF_PROJECT}_user\nDB_PASS:$DB_PASS\nDirectory Project:$HOME/$WORK_DIR/$NAME_OF_PROJECT/" >> ~/$WORK_DIR/$NAME_OF_PROJECT/config.txt
echo "*************************************"
echo -e "\033[1mЛокальный сайт готов к работе.Файл конфигурации находится в $HOME/$WORK_DIR/$NAME_OF_PROJECT/\033[0m"
